#Nome da aplicação
spring.application.name=Pizzaria

#Configuração do banco de dados
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

#Configuração do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#Configuração da chave secreta do JWT
jwt.secret=${JWT_SECRET}