CREATE TABLE tb_usuarios(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    permissao VARCHAR(100) NOT NULL
);

CREATE TABLE tb_produtos(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tipoProduto VARCHAR(255) NOT NULL,
    preco NUMERIC(10,2) NOT NULL
);

CREATE TABLE tb_pedidos(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total NUMERIC(10,2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    idCliente INTEGER NOT NULL,

    CONSTRAINT fk_pedido_cliente
                       FOREIGN KEY (idCliente)
                       REFERENCES tb_usuarios(id)
);

CREATE TABLE tb_item_pedido(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idPedido INTEGER NOT NULL,
    idProduto INTEGER NOT NULL,
    precoUnitario NUMERIC(10,2) NOT NULL,
    quantidade INTEGER NOT NULL,

    CONSTRAINT fk_item_pedido
                           FOREIGN KEY (idPedido)
                           REFERENCES tb_pedidos(id),
    CONSTRAINT fk_item_produto
                           FOREIGN KEY (idProduto)
                           REFERENCES tb_produtos(id)
);

