CREATE TABLE tb_usuarios(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    permissao VARCHAR(100) NOT NULL
);

CREATE TABLE tb_produtos(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tipo_produto VARCHAR(255) NOT NULL,
    preco NUMERIC(10,2) NOT NULL
);

CREATE TABLE tb_pedidos(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total NUMERIC(10,2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    id_cliente INTEGER NOT NULL,

    CONSTRAINT fk_pedido_cliente
                       FOREIGN KEY (id_cliente)
                       REFERENCES tb_usuarios(id)
);

CREATE TABLE tb_item_pedido(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL,
    id_produto INTEGER NOT NULL,
    preco_unitario NUMERIC(10,2) NOT NULL,
    quantidade INTEGER NOT NULL,

    CONSTRAINT fk_item_pedido
                           FOREIGN KEY (id_pedido)
                           REFERENCES tb_pedidos(id),
    CONSTRAINT fk_item_produto
                           FOREIGN KEY (id_produto)
                           REFERENCES tb_produtos(id)
);

